apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"

  template:
    metadata:
      labels:
        app: "frontend"

    spec:
      containers:
        - name: "frontend"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: "VITE_API_BASE"
              value: "http://localhost:{{ .Values.apiGateway.port }}"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      name: http
