apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-service
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-worker
  namespace: default