secret:
  POSTGRES_USER_AUTH: "REPLACE_ME"
  POSTGRES_PASSWORD_AUTH: "REPLACE_ME"
  POSTGRES_DB_AUTH: "REPLACE_ME"
  POSTGRES_USER_TASK: "REPLACE_ME"
  POSTGRES_PASSWORD_TASK: "REPLACE_ME"
  POSTGRES_DB_TASK: "REPLACE_ME"
  MONGO_INITDB_ROOT_USERNAME: "REPLACE_ME"
  MONGO_INITDB_ROOT_PASSWORD: "REPLACE_ME"

domain: "REPLACE_ME"
tlsSecret: "REPLACE_ME"

jwt:
  key: "REPLACE_ME"
  issuer: "REPLACE_ME"
  audience: "REPLACE_ME"
